name: Release

on:
  push:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build & Release (x64)
    runs-on: windows-2025-vs2026
    steps:
      - name: Check out source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Generate docs
        run: bun .\cmd\gen-docs.ts

      - name: Build Release x64
        run: msbuild vs2026/SumatraPDF.slnx /t:SumatraPDF:Rebuild;SumatraPDF-dll:Rebuild /p:Configuration=Release;Platform=x64 /m

      - name: Prepare Release Artifact
        shell: pwsh
        run: |
          if (-not (Test-Path "out\rel64\SumatraPDF.exe")) {
              Write-Error "SumatraPDF.exe not found!"
              exit 1
          }
          $files = @("out\rel64\SumatraPDF.exe")
          if (Test-Path "out\rel64\libmupdf.dll") { $files += "out\rel64\libmupdf.dll" }
          Compress-Archive -Path $files -DestinationPath "SumatraPDF-x64.zip" -Force

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: SumatraPDF-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
