name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v3.5.0
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build & Release
    runs-on: windows-2025-vs2026
    steps:
      - name: Check out source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'

      - name: Generate docs
        run: bun .\cmd\gen-docs.ts

      - name: Build Release x64
        run: msbuild vs2026/SumatraPDF.slnx /t:SumatraPDF:Rebuild /p:Configuration=Release /p:Platform=x64 /m

      - name: Build Release x86
        run: msbuild vs2026/SumatraPDF.slnx /t:SumatraPDF:Rebuild /p:Configuration=Release /p:Platform=x86 /m

      - name: Prepare Release Artifacts
        shell: pwsh
        run: |
          $artifacts = @()
          if (Test-Path -Path "out\rel64\SumatraPDF.exe") {
              Compress-Archive -Path "out\rel64\SumatraPDF.exe" -DestinationPath "SumatraPDF-x64.zip" -Force
              $artifacts += "SumatraPDF-x64.zip"
          }
          if (Test-Path -Path "out\rel32\SumatraPDF.exe") {
              Compress-Archive -Path "out\rel32\SumatraPDF.exe" -DestinationPath "SumatraPDF-x86.zip" -Force
              $artifacts += "SumatraPDF-x86.zip"
          }
          
          if ($artifacts.Count -eq 0) {
              Write-Error "No built binaries found to release!"
              exit 1
          }

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SumatraPDF-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
